#!/bin/bash
cd /home/ubuntu/workspace
# Flask APP
export FLASK_APP=handbook
# Debug mode
export FLASK_DEBUG=1
#======================
# Ensure conditions in setup.py is met
sudo pip install -e .
# Run the application
flask run --host=0.0.0.0 --port=8080
