#!/bin/bash
cd /home/ubuntu/workspace
# Flask APP
export FLASK_APP=handbook
# Debug mode
# export FLASK_DEBUG=true
#======================

# Ensure conditions in setup.py is met
sudo pip install -e .
# Run the application
python -m flask run
